### PR TITLE
Dependency changes and syntax changes 

### PR DESCRIPTION
**Pull request by abhishekpadalkar**
removed mas_third_party_softwares .... no longer required

### CODE REVIEW

**Review by argenos — CHANGES_REQUESTED** [review]
Was `mercury_planner` moved to `mas_industrial`? I think that requires `mcr_task_planning` to be moved as well. The dependency to the package is not explicit in the `package.xml`, but it should be there.

**Comment by abhishekpadalkar** [comment]
`mercury_planner` is on github as a separate repo and it was added in unmerged_packages dependencies... But cannot see unmerged here ..

**Comment by argenos** [comment]
I know. The only thing missing is moving `mcr_task_planning` to `mas_industrial`

**Comment by argenos** [comment]
Changes here are also no longer only about `mas_third_party_software`, for the next pull request please keep them on separate branches

**Pull request closed without merging**
