### PR TITLE
Added files for pose calculation using FK

### PR DESCRIPTION
**Pull request by iswariyam**
Link pose is calculated using forward kinematics

* the pose of any link(s) is be calculated using forward kinematics (from moveit)
* the pose is calculated with respect to any valid reference frame
* the desired joint configurations from the SRDF can be given before calculating the pose

## Changelog
* Added two functions in kinematics.py
    - one for parsing the SRDF to extract the desired joint configuration
    - another for computing the link(s) poses with respect to a reference frame

## Related PRs
Related to [issue 103](https://github.com/b-it-bots/mas_industrial_robotics/issues/103#issue-561228171)

## Checklist:
- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)

### CODE REVIEW

**Comment by iswariyam** [comment]
@sthoduka I have made this functionality into a class as requested by @DharminB .
@DharminB Please try to import this class in the perceive_drawer_handle module and let me know if there are any issues.

**Comment by alex-mitrevski** [comment]
@iswariyam Isn't this the same functionality as in [`mcr_manipulation_utils/kinematics.py`](https://github.com/b-it-bots/mas_common_robotics/blob/kinetic/mcr_manipulation/mcr_manipulation_utils/ros/src/mcr_manipulation_utils_ros/kinematics.py)?

**Comment by iswariyam** [comment]
@alex-mitrevski  yes, indeed get_link_pose() calls forward_kinematics(). But @DharminB wanted it to be a class to avoid replication of parsing the SRDF and having to set the header values at multiple places. This class and its methods can now be called with a single line code at many places, where it is required to calculate the pose of a link (e.g. end-effector) for a specific joint configuration, with respect to a particular frame.

**Comment by alex-mitrevski** [comment]
Then this looks like a design that can be improved. I think a class is not necessary here; in fact, the name itself violates what a class is about (`CalculateLinkPose` is what a function would be named).

I think it would make more sense to refactor the `Kinematics` class in `kinematics.py` to suit your needs, or alternatively, add your two functions to that script (not within the class) and add the group name as an additional argument to both. Semantically, the functions belong there.

**Comment by iswariyam** [comment]
@alex-mitrevski  Moved the code to kinematics.py.

**Comment by alex-mitrevski** [comment]
@iswariyam Could you please also update the PR description to reflect these changes? Thanks!

**Review by alex-mitrevski — APPROVED** [review]

**Review by sthoduka — APPROVED** [review]

**Comment by iswariyam** [comment]
> @iswariyam Could you please also update the PR description to reflect these changes? Thanks!

Done!

**Review by argenos — APPROVED** [review]

**Pull request merged**
