### PR TITLE
[arm cartesian control] Added code for accessing sigma values

### PR DESCRIPTION
**Pull request by abhishekpadalkar**

### CODE REVIEW

**Review by argenos — DISMISSED** [review]
Since this is using the new kdl version, then the rosinstall file needs to be updated. This is probably why the Travis build fails.

**Comment by argenos** [comment]
There is also an error with `mcr_time_parametrizer`, although I'm not sure if unrelated to this:
```

/opt/ros/kinetic/lib/liburdf.so: undefined reference to `rosconsole_bridge::RegisterOutputHandlerProxy::~RegisterOutputHandlerProxy()'
collect2: error: ld returned 1 exit status
CMakeFiles/trajectory_time_parameterizer.dir/build.make:232: recipe for target '/kinetic/devel/.private/mcr_trajectory_time_parameterizer/lib/mcr_trajectory_time_parameterizer/trajectory_time_parameterizer' failed
make[2]: *** [/kinetic/devel/.private/mcr_trajectory_time_parameterizer/lib/mcr_trajectory_time_parameterizer/trajectory_time_parameterizer] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/trajectory_time_parameterizer.dir/all' failed
make[1]: *** [CMakeFiles/trajectory_time_parameterizer.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
/kinetic

```

**Comment by argenos** [comment]
```/opt/ros/kinetic/lib/liburdf.so: undefined reference to `rosconsole_bridge::RegisterOutputHandlerProxy::~RegisterOutputHandlerProxy()'collect2: error: ld returned 1 exit statusCMakeFiles/trajectory_time_parameterizer.dir/build.make:232: recipe for target '/kinetic/devel/.private/mcr_trajectory_time_parameterizer/lib/mcr_trajectory_time_parameterizer/trajectory_time_parameterizer' failedmake[2]: *** [/kinetic/devel/.private/mcr_trajectory_time_parameterizer/lib/mcr_trajectory_time_parameterizer/trajectory_time_parameterizer] Error 1CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/trajectory_time_parameterizer.dir/all' failedmake[1]: *** [CMakeFiles/trajectory_time_parameterizer.dir/all] Error 2Makefile:138: recipe for target 'all' failedmake: *** [all] Error 2/kinetic```

**Comment by argenos** [comment]
After further investigation, the problem with rosconsole bridge in docker can be fixed after `apt upgrade`. 

There is however another issue when the catkin workspace is configured with an install space:

```
CMakeFiles/arm_cartesian_control.dir/ros/src/arm_cartesian_control_node.cpp.o: In function `jointstateCallback(boost::shared_ptr<sensor_msgs::JointState_<std::allocator<void> > const>)':
arm_cartesian_control_node.cpp:(.text+0xa2): undefined reference to `KDL::Chain::getSegment(unsigned int)'
CMakeFiles/arm_cartesian_control.dir/ros/src/arm_cartesian_control_node.cpp.o: In function `init_joint_msgs()':
arm_cartesian_control_node.cpp:(.text+0xc86): undefined reference to `KDL::Chain::getSegment(unsigned int)'
collect2: error: ld returned 1 exit status
CMakeFiles/arm_cartesian_control.dir/build.make:155: recipe for target '/kinetic/devel/.private/mcr_arm_cartesian_control/lib/mcr_arm_cartesian_control/arm_cartesian_control' failed
make[2]: *** [/kinetic/devel/.private/mcr_arm_cartesian_control/lib/mcr_arm_cartesian_control/arm_cartesian_control] Error 1
CMakeFiles/Makefile2:782: recipe for target 'CMakeFiles/arm_cartesian_control.dir/all' failed
make[1]: *** [CMakeFiles/arm_cartesian_control.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

To reproduce you can set your catkin workspace using `catkin config --install`

**Comment by abhishekpadalkar** [comment]
I don't have the exact environment as the @b-it-bots/home team members, hence I cannot reproduce the error. But i will tray to add new version of KDL and create a PR.

**Comment by minhnh** [comment]
@abhishek098 can you start from a clean system with only ros-desktop installed? This can be done with either VM or docker image.

**Comment by argenos** [comment]
@abhishek098 can you merge/rebase the changes from kinetic here?

**Comment by abhishekpadalkar** [comment]
Travis CI build passed. There is issue with the quality of code saying "variable not used" but thats ok, its the error code which can be used in future for further investigation in arms capabilities of executing motion. This branch can be merged now.

**Comment by argenos** [comment]
@abhishek098 you should be able to see what the problem is by clicking on Details next to Codacy. Good news is, it was complaining about sigma not being used, so I've ignored the warning.

**Review by argenos — APPROVED** [review]

**Review by alex-mitrevski — APPROVED** [review]

**Pull request merged**
